services:
  web-capture:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - PORT=3000
